site_name: Cloud Custodian Documentation
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - tabs
    - instant
    - search.suggest
    - search.highlight
    - search.share
plugins:
  - minify:
      minify_html: true
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: iso_datetime
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      toc_depth: 1
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed
  - pymdownx.details

copyright: "Copyright © 2021 The Cloud Custodian Authors"